apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: guestbook_template
  title: Guestbook Project Template
  description: Create a Nodejs component
  tags:
    - nodejs
    - mongodb
    - hackathon
spec:
  owner: devs@globex.com
  type: service
  parameters:
    - title: Provide component information
      required:
        - name
      properties:
        name:
          title: Name of the component
          type: string
          description: Name of the component
        organization:
          title: Organization Name
          type: string
          default: globex-org
        owner:
          title: Component Owner
          type: string
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: User
        ci:
          title: Select a CI method
          type: string
          description: This action will create a CI pipeline for your application
          default: ../../../skeletons/github-actions/
          enum:
            - ../../../skeletons/tekton/
          enumNames:
            - OpenShift Pipelines
        registry:
          title: Select Image Registry
          type: string
          description: This action will push the container image to the selected registry
          default: ../../../skeletons/quay/
          enum:
            - ../../../skeletons/quay/
          enumNames:
            - Quay.io
   
  steps:
    - action: debug:wait
      id: build-wait
      name: Build Application
      input:
        seconds: 2
    - action: debug:wait
      id: ci-wait
      name: Provision CI/CD
      input:
        seconds: 3
    - action: debug:wait
      id: push-wait
      name: Push to image Registry
      input:
        seconds: 4
    - action: debug:wait
      id: register-wait
      name: Register Component in Catalog
      input:
        seconds: 1
  
  output:
    links:
      - title: Open the Source Code Repository
        URL: "https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates/github/nodejs-backend/template.yaml"
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: "https://backstage-rhdh-rhdh-operator.apps.cluster-ms72l.sandbox990.opentlc.com/catalog?filters%5Bkind%5D=user&filters%5Buser%5D=all"
